version = 1

exclude_patterns = [
    "/docs/docs",
    "bijou.js",
    "bijou-min.js",
    "bijou_node.js"
]

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
