version = 1

exclude_patterns = [
    "docs/docs",
    "bijou.js",
    "bijou-min.js",
    "bijou_node.js",
    "js/_end.js",
    "js/_copyright.js"
]

[[analyzers]]
name = "javascript"
enabled = true
