on:
 workflow_dispatch:
 push:
 schedule:
   - cron: 0 0 * * *
 pull_request:
   types: [opened, synchronize, reopened, closed]
name: Build + compile
jobs:
 release:
   name: Build + compile
   runs-on: ubuntu-latest
   steps:
     - run: echo "${{ toJson(github) }}"
     - name: Build and compile
       uses: technote-space/create-pr-action@v2
       with:
         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         EXECUTE_COMMANDS: |
           sudo npm install;
           sudo npm i -g eslint --loglevel verbose
           sudo npm i -g prettier --loglevel verbose
           sudo npm i -g terser --loglevel verbose
           sudo npm i -g jsdoc --loglevel verbose
           sudo npm i -g rollup --loglevel verbose
           sudo npm i -g figlet-cli --loglevel verbose
           sudo npm i -g jsdoc-to-markdown --loglevel verbose
           rm bijou_node.js
           rm bijou.js
           cat ./js/_copyright.js ./js/array.js ./js/color.js ./js/date.js ./js/element.js ./js/event.js ./js/function.js ./js/object.js ./js/math.js ./js/string.js ./js/utility.js ./js/_end.js > bijou.js
           rm -r docs/docs
           rm bijou-min.js
           jsdoc -c jsdoc.json
           sudo eslint --fix ./ || eslint --fix ./ || ls
           prettier --write -- .
           rollup bijou.js --file bijou_node.js --format cjs
           terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o docs/bijou.js -- bijou.js
           terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o bijou-min.js -- bijou.js
           jsdoc2md bijou.js > documentation.md
         COMMIT_MESSAGE: "Automated build"
         COMMIT_NAME: 'Build bot'
         COMMIT_EMAIL: 'explosionscratch@gmail.com'
         PR_BRANCH_NAME: 'build-pr-${PR_NUMBER}'
         PR_TITLE: 'Build and compile ${PR_NUMBER_REF}'
