on:
 workflow_dispatch:
 push:
 schedule:
   - cron: 30 * * * *
 pull_request:
   types: [opened, synchronize, reopened, closed]
name: Build + compile
jobs:
 echo:
   name: Echo github
   runs-on: ubuntu-latest
   steps:
      - name: Spill secrets (lol)
        env:
          GITHUB_CONTEXT: ${{ secrets.GITHUB_EVENT_NAME }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
 release:
   if: github.actor != 'Explosion-Scratch' || ${{ secrets.GITHUB_EVENT_NAME }} != 'pull_request'
   name: Build + compile
   runs-on: ubuntu-latest
   steps:
     - name: Build and compile
       uses: technote-space/create-pr-action@v2
       with:
         EXECUTE_COMMANDS: |
           sudo npm install;
           sudo npm i -g eslint
           sudo npm i -g prettier
           sudo npm i -g terser
           sudo npm i -g jsdoc
           sudo npm i -g rollup
           sudo npm i -g figlet-cli
           sudo npm i -g jsdoc-to-markdown
           rm bijou_node.js
           rm bijou.js
           cat ./js/_copyright.js ./js/array.js ./js/color.js ./js/date.js ./js/element.js ./js/event.js ./js/function.js ./js/object.js ./js/math.js ./js/string.js ./js/utility.js ./js/_end.js > bijou.js
           rm -r docs/docs
           rm bijou-min.js
           jsdoc -c jsdoc.json
           sudo eslint --fix ./ || eslint --fix ./ || ls
           prettier --write -- .
           rollup bijou.js --file bijou_node.js --format cjs
           terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o docs/bijou.js -- bijou.js
           terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o bijou-min.js -- bijou.js
           jsdoc2md bijou.js > documentation.md
         COMMIT_MESSAGE: "Automated build"
         COMMIT_NAME: 'Build bot'
         COMMIT_EMAIL: 'explosionscratch@gmail.com'
         PR_BRANCH_NAME: 'build-pr-${PR_NUMBER}'
         PR_TITLE: 'Build and compile ${PR_NUMBER_REF}'
