name: Update Docs

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Docs]')"

    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Generate docs
          repo: Bijou-js/bijou.js.org
          token: ${{ steps.generate-token.outputs.token }}
          ref: refs/heads/master
