on: [pull_request, workflow_dispatch, push]
name: Automated CI
jobs:
 git-bat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: ls
      - run: npm install
      - run: sudo npm i -g rollup eslint jsdoc prettier terser
      - run: rm -f bijou_node.js
             && rm -f bijou.js
      - run: cat ./js/_copyright.js ./js/array.js ./js/color.js ./js/date.js ./js/element.js ./js/event.js ./js/function.js ./js/object.js ./js/math.js ./js/string.js ./js/utility.js ./js/_end.js > bijou.js
      - run: rm -rf docs/docs
             && rm -f bijou-min.js
      - run: jsdoc -c jsdoc.json
             && prettier --write -- .
      - run: rollup bijou.js --file bijou_node.js --format cjs
             && terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o docs/bijou.js -- bijou.js
             && terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o bijou-min.js -- bijou.js
      - run: prettier --write ./
      - run: git add --force docs/docs
      - run: git add --force bijou.js && git add --force bijou-min.js && git add --force bijou_node.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Building files

        
