on: [pull_request, workflow_dispatch, push]
name: Automated CI
jobs:
 git-bat:
    if: "contains(github.event.head_commit.message, '[Actions]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: ls
      - run: ./git.bat
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Applying automated CI items

        
