on: [push, pull_request]
name: Automated CI
jobs:
 git-bat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: sudo npm i -g showdown terser prettier figlet-cli
      - run: prettier --quote-props=consistent --trailing-comma=all --no-semi --write -- ./
      - run: terser --compress --mangle -o bijou-min.js -- bijou.js
      - run: showdown makehtml -i README.md -o README.html
      - run: |
             COMMIT_FILE=$(git diff --name-only)
             DATE=$(date +"%F %H:%M:%S")
             USER=$(git config user.name)
             EMAIL=$(git config user.email)
             REPO="BIJOU.JS"
             FIGLET_REPO=$(figlet -kf Big -- $REPO)
             BR=$'\n'
             COMMIT_MSG=$"${FIGLET_REPO}${BR}Files changed: ${BR}${BR}${COMMIT}${BR}${BR}Date: ${DATE}${BR}User: ${USER}${BR}Email: ${EMAIL}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: ${COMMIT_MSG} ${COMMIT_FILE}

        
