on: [pull_request, workflow_dispatch, push]
name: Automated CI
jobs:
 git-bat:
    if: "contains(github.event.head_commit.message, '[Actions]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: ls
      - run: npm install
      - run: sudo npm i -g rollup eslint eslint-plugin-jsdoc jsdoc prettier terser figlet-cli
      - run: COMMIT=$(git status --porcelain)
      - run: rm bijou_node.js
             && rm bijou.js
      - run: cat ./js/_copyright.js ./js/array.js ./js/color.js ./js/date.js ./js/element.js ./js/event.js ./js/function.js ./js/object.js ./js/math.js ./js/string.js ./js/utility.js ./js/_end.js > bijou.js
      - run: rm -r docs/docs
             && rm bijou-min.js
      - run: jsdoc -c jsdoc.json
             && prettier --write -- .
      - run: rollup bijou.js --file bijou_node.js --format cjs
             && terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o docs/bijou.js -- bijou.js
             && terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o bijou-min.js -- bijou.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Applying automated CI items

        
