on: [push, pull_request]
jobs:
 git-bat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: chmod u+x ./git.bat
      - run: ./git.bat
      - uses: stefanzweifel/git-auto-commit-action@v4

        
