on: [push, pull_request]
name: Run Git.bat
jobs:
 git-bat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      - run: cd
      - run: chmod u+x ./git.bat
      - run: ./git.bat
