name: GitHub pages

on:
  workflow_dispatch

jobs:
  jsdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: sudo npm i -g jsdoc
      - run: rm -r ./docs
      - run: jsdoc -c ./jsdoc.json
      - run
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: JS docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
