name: JS Docs

on:
  workflow_dispatch
  # push:
    # branches:
      # - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./
          output_dir: ./docs
          template: docdash
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
