name: 'Commit Message Check'
on:
  push

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^v[0-9].[0-9].[0-9]'
          flags: 'gm'
          error: 'This commit does not release a version'
      - name: Release
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: NPM Config
        run: git config user.email "explosionscratch@gmail.com"
      - name: More config
        run: git config user.name "Explosion-Scratch"
      - name: NPM version
        run: npm version ${{ github.event.head_commit.message }} --allow-same-version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: Release ${{ github.event.head_commit.message }}
          body: |
            Automated release, version ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        
