on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: 'v'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: NPM Config
        run: git config user.email "explosionscratch@gmail.com"
      - name: More config
        run: git config user.name "Explosion-Scratch"
      - name: NPM version
        run: npm version ${{ github.event.inputs.version }} --allow-same-version
      - run: git stage .
      - run: git push
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
