on:
 workflow_dispatch:
name: Build + compile
jobs:
 release:
   name: Build + compile
   runs-on: ubuntu-latest
   steps:
     - name: Build and compile
       uses: technote-space/create-pr-action@v2
       with:
         EXECUTE_COMMANDS: |
           rm bijou.js
           cat ./js/_copyright.js ./js/array.js ./js/color.js ./js/date.js ./js/element.js ./js/event.js ./js/function.js ./js/object.js ./js/math.js ./js/string.js ./js/utility.js ./js/_end.js > bijou.js
         COMMIT_MESSAGE: "Automated build"
         COMMIT_NAME: 'Build bot'
         COMMIT_EMAIL: 'explosionscratch@gmail.com'
         PR_BRANCH_NAME: 'build-pr-${PR_NUMBER}'
         PR_TITLE: 'Build and compile ${PR_NUMBER_REF}'
